-- Load core options
require("core.options")
require("core.lazy")
require("core.keymap")
require("core.autocmds")
require("core.lsp")
vim.cmd.colorscheme("catppuccin")
-- require("scope.init")
require("core.indent-guide")
require("core.filetype")
